### ISSUE TITLE
Reviews aren't being uploaded even though I'm online. 

### ISSUE THREAD

**Issue by komocode** [davidsansome/tsurukame#122]
![IMG_0692](https://user-images.githubusercontent.com/226526/57737453-9decf180-7660-11e9-94c0-afc5babf71da.png)

**Comment by davidsansome** [comment]
Thanks for reporting this!  It's a problem caused by a recent change to WaniKani that started expiring auth cookies.

I think I've fixed it now!  Would you mind installing a new version from testflight, and let me know if it works?  https://testflight.apple.com/join/Fijye2AA

**Comment by komocode** [comment]
I installed it just now without deleting the app. It seems to still show "225 review progress:

**Comment by indirect** [comment]
Sadly I am also seeing this, running from the latest commit ca4cad025e848ad2947411e14b3e89764c8808f3.

**Comment by indirect** [comment]
Hmm... I have no idea, now. I installed a build without the API changing commit, and it was able to upload pending reviews. Then I deleted the app, re-installed the exact previous build that couldn't upload pending reviews, and... it uploaded a new set of pending reviews just fine. 😬

**Comment by lyallcooper** [comment]
I experienced the same issue with the testflight build, where it couldn't upload lesson/review progress, but reverting to the app store version uploaded them fine. However after reinstalling the testflight build it _still_ couldn't upload progress, unlike @indirect.

**Comment by indirect** [comment]
To be clear, it seems to work for me if I delete the app entirely before installing the new build with this change—upgrading in place by installing this change over the old build seems to make things get stuck. At least for me.

**Comment by indirect** [comment]
My iPad got into a super weird state: 4 reviews queued to be uploaded "when I'm back online", but doing new reviews immediately uploaded them. Without uploading those 4 queued reviews. I'm very sure the "live" reviews were making it to the server because I got an level-up email from Koichi while I was testing to see if new reviews would get uploaded... but those 4 queued reviews never did get uploaded. I had to log out and log back in to make them go away.

**Comment by indirect** [comment]
Oh weird... logging out and then logging back in seems to have gotten it into a state where nothing gets uploaded to the server and everything gets queued. 😲

**Comment by indirect** [comment]
As far as I can tell, this was fixed for me by #138. Is anyone else still seeing it?

**Comment by brookshelley** [comment]
Just started seeing this with the latest update—I’m online and 82 reviews are showing as “will be uploaded when you’re back online”

**Comment by indirect** [comment]
@brookshelley any chance you can collect console logs while refreshing? I think it ought to say what you're getting back from the server if it's not a 200.

**Comment by indirect** [comment]
Sorry, that was maybe too cryptic to be helpful. Any chance you can connect your device to a Mac running Xcode and open the devices panel and collect the console logs from Tsurukame while refreshing? Also hi! 👋 Always nice to run into a familiar face. 😄

**Comment by brookshelley** [comment]
Oh, hey Andre! I didn’t know you made this—If it happens again I totally can. I logged out and back in, and things seem to be working again. I had to redo my lessons, but that was probably helpful for me, tbh.

Additional details from before: iOS 13 dev beta 7 on iPad and iPhone—updated right before leveling up, and running through a bunch of lessons.

**Comment by indirect** [comment]
Haha yeah, the app was so good I started contributing to it, including the fix mentioned earlier in this ticket when some reviews were getting stuck for me. If it happens to you again, I'd be happy to take a look at the logs and see if I can figure it out.

**Comment by brookshelley** [comment]
Rad! Yea this app rules and makes it such that I barely go to Wanikani’s site anymore.
What level are you on? I’ve got a Japan business trip in a few months so i’ve been powering through levels as fast as I can

**Comment by bulkan** [comment]
I'm seeing this in the latest update as well.

**Comment by indirect** [comment]
@brookshelley just hit 20! this app has definitely been part of how I've been able to keep up :tada:

@bulkan can you try deleting the app outright, or logging out and back in, and let us know if it happens again?

**Comment by indirect** [comment]
AHA that actually makes everything make sense to me now. The endpoint change means you need to log out and back in after upgrading. If no one else gets to it sooner, I can probably work up a fix this weekend.

**Comment by bulkan** [comment]
@indirect I logged out and logged in again and it's uploaded.

**Comment by brookshelley** [comment]
@indirect rad! Yea it rules. I just hit 26

**Comment by usako88** [comment]
Updated to version 1.11 and reviews are not syncing. Somebody wrote that logging out will cost you our progress so far. Is this true? I dont want to risk that

**Comment by indirect** [comment]
@usako88 those reviews are already lost; right now there's no way to upload them. (If you're good at iOS development, you could use this repo to install a build from before the upload endpoint change, or you could wait until someone writes a fix and commits it here.)

Again: there's no way to upload those reviews. You need to log out and back in to be able to upload future reviews. Sorry.

**Comment by indirect** [comment]
Fixed by https://github.com/davidsansome/tsurukame/commit/4ed6a17f153821fdde603ed24fbe51070b67112f.

**Comment by davidsansome** [comment]
Sorry about all this. There's a fix on the way. **Don't** log out and log back in again - the new version will be able to upload your saved reviews.
