### ISSUE TITLE
Notification badge not updating in the background

### ISSUE THREAD

**Issue by abdulajet** [davidsansome/tsurukame#501]
i'm running the iOS 15 beta so not sure if that is the issue but my notifications badge doesn't seem to update in the background anymore. has there been any change around that?

**Comment by UInt2048** [comment]
No, there hasn't. I'll keep an eye out to see if I'm experiencing that too.

**Comment by UInt2048** [comment]
I can confirm on iOS 14 that the notification count can be incorrect. I'm curious as to whether this is due to the operating system, or something fixable by the app.

**Comment by abdulajet** [comment]
yeah im not sure, it was working before! I see there has been some changes to the LocalCachingClient class in the past few weeks

**Comment by bmironer** [comment]
for the record, as there seems to be more discussions on this.
on my setup this currently only happens in my custom build on macOS, not on the TestFlight beta.
my specific symptom is that the badge shows a very high count as if it was cached or updated every hour in the background without actually loading the data (I haven't precisely timed it though)
And the badge is only updated with the correct count when I quit the app or force a reload. 
And then continues to go up incorrectly by itself...

Also worth mentionning : I'm using the app both on mac (custom mac build) and on my phone (testflight build) throughout the day.

**Comment by UInt2048** [comment]
@bmironer If you’re reviewing elsewhere, Tsurukame doesn’t know about that until you open it.

**Comment by bmironer** [comment]
yes, obviously.  but this is a different issue : it's only happens on the mac, not on iOS. 
as I type this, the iOS badge shows 40 and the macOS one shows... 382!
iOS is correct although I did not use it this morning.
macOS shows this (see screenshot)
<img width="666" alt="Screenshot 2022-03-23 at 11 56 12" src="https://user-images.githubusercontent.com/50280/159684148-51f63d9c-c608-4b6a-b17b-862cc635c4fe.png">

**Comment by UInt2048** [comment]
@bmironer That is pretty weird - not what I thought you were saying

**Comment by davidsansome** [comment]
The original issue (badge count not updating) should be fixed now. The issue was that Tsurukame schedules a whole bunch of future badge updates (and notifications if you have them enabled) in advance every time you open the app. iOS only allows apps to schedule a maximum of 64 notifications. We used to only schedule 48 notifications (covering the next 2 days) but 569c095f9ca162e21171ebd92931a5ca512c3b24 accidentally removed that limit and scheduled **all** the notifications for all your future reviews every time. When the app adds the 65th notification, iOS removes the 1st one, and so on, so all the earliest scheduled notifications ended up getting removed.

> If you’re reviewing elsewhere, Tsurukame doesn’t know about that until you open it.

That's not true. Tsurukame registers for iOS background app refreshes to do a quick sync and update the badge count and schedule new notifications. They happen whenever iOS decides to - usually every few hours, more frequently if you've got a full battery, etc.

> as I type this, the iOS badge shows 40 and the macOS one shows... 382!

I have no idea why this would happen!

**Comment by UInt2048** [comment]
> Tsurukame registers for iOS background app refreshes to do a quick sync and update the badge count and schedule new notifications.

Sorry about that, it doesn’t for me since I keep background app refresh off, so there’s none given to Tsurukame…

**Comment by bmironer** [comment]
Ok it's still not working on macOS. I added a log to the notification registration and it does only add 64 items with the same values as the upcoming values table view.

```
added notification: <UNNotificationRequest: 0x600001bf0120; identifier: badge-0, content: <UNNotificationContent: 0x60000294d500; title: (null), subtitle: (null), body: (null), summaryArgument: , summaryArgumentCount: 0, categoryIdentifier: , launchImageName: , threadIdentifier: , attachments: (
), badge: 72, sound: (null), realert: 0, interruptionLevel: 1, relevanceScore: 0.00, trigger: <UNTimeIntervalNotificationTrigger: 0x60000159a680; repeats: NO, timeInterval: 3060.372727>>
added notification: <UNNotificationRequest: 0x600001bf18c0; identifier: badge-1, content: <UNNotificationContent: 0x60000294e800; title: (null), subtitle: (null), body: (null), summaryArgument: , summaryArgumentCount: 0, categoryIdentifier: , launchImageName: , threadIdentifier: , attachments: (
), badge: 79, sound: (null), realert: 0, interruptionLevel: 1, relevanceScore: 0.00, trigger: <UNTimeIntervalNotificationTrigger: 0x60000159a900; repeats: NO, timeInterval: 6660.372727>>
```

However it just jumped from 41 to 517 instead of 72. And this is not a value from the list. 
So it seems there are old notification not being cleared by removeAllPendingNotificationRequests()

And I just found this : 


https://stackoverflow.com/questions/61433912/calling-removeallpendingnotificationrequests-in-applicationwillterminate-not-w

Could it be the issue?

**Comment by bmironer** [comment]
ok this is getting weirder : the notifications (now working again) are showing the correct number. 
It's only the badge that isn't.

**Comment by bmironer** [comment]
I was indeed receiving double notifications on the hour : the correct one, and a seemingly older one with a very large count.

I think I finally sorted it out by removing the app from the list in the notification panel in System Preferences and re-authorizing notification in the app. 
It seems to have cleared the bad backlog.

**Comment by bmironer** [comment]
aaand it's back
<img width="368" alt="Screenshot 2022-03-29 at 09 00 36" src="https://user-images.githubusercontent.com/50280/160553592-51231954-5e64-4eb4-bd3d-27aaf92de47b.png">
.
