### ISSUE TITLE
[BUG](iPhone) app crashes on server sync

### ISSUE THREAD

**Issue by WyattLuke** [davidsansome/tsurukame#632]
When I open the app it crashes as soon as it starts syncing with the wanikani server. Im able to use the app if I disable my phone’s internet access. But if I turn it on again the app crashes as soon as it starts syncing. Assuming that there was some update to how Wanikani’s api works, or unexpected data was retrieved? Could just be me of course, as I haven’t seen any mention of this yet from anyone online. 

I heard that they were adding non kanji words to Wanikani, I don’t have access to a computer at the moment to check if that might be the cause.

Love the app, probably a big reason I’ve gotten as far as I have

**Comment by skochinsky** [comment]
I've had the same issue but it went away afer updating to 1.27 released a few days ago. The release notes said "Compatibility with the upcoming Wanikani kana-only vocab feature", so probably the feature just went live and started crashing old versions.

**Comment by WyattLuke** [comment]
> I've had the same issue but it went away afer updating to 1.27 released a few days ago. The release notes said "Compatibility with the upcoming Wanikani kana-only vocab feature", so probably the feature just went live and started crashing old versions.

I can confirm that this fixed the issue, I checked for updates but I guess I missed it somehow

**Comment by davidsansome** [comment]
Yes, 1.27 should fix this crash. I released it to 100% of users yesterday, but I guess it'll take some phones a while to update.

**Comment by nickkossolapov** [comment]
I started getting this issue a few hours ago, but it was still crashing for me. I tried to delete and redownload the app, but now I can't login and it just says "Unknown error". It seems I did download 1.27 from the app store?

**Comment by davidsansome** [comment]
> I can't login and it just says "Unknown error"

Make sure you're using your **email address** instead of your username to login - WaniKani changed that last month :/

**Comment by nickkossolapov** [comment]
@davidsansome  Ah, I was using the wrong email. It looks like my update with just slow, and the reinstall fixed the issue. Thanks!
